import argparse
import os

def parse_bool(input_string):
    if input_string not in {'True','False'}:
        raise argparse.ArgumentTypeError("Value has to be True or False !")
    if input_string =='True':
        return True
    else:
        return False
    
def parse_file(input_filename):
    if not os.path.isfile(input_filename):
        raise argparse.ArgumentTypeError("File does not exist. Please use a valid file path.")
    return(input_filename)
    
parser=argparse.ArgumentParser(description="Script to get Top Barcodes for Chrono-Seq DGE creation")
parser.add_argument("FILENAME",help="txt.gz file generated by DropSeq tools program BAMTagHistogram using XC as the Tag",type=parse_file)

parser.add_argument("-np","--NUM_PLOT", help="Number of Cells to Plot for the Cumulative Barcode Plot, Default Value is 500",type=int)
parser.add_argument("-ne","--NUM_EXPORT",help="Number of Cells to Export for DGE creation.\n"+
                    "This should be determined from the knee in the plot generated by this script.\n"+
                    "If this argument is not specified no barcode list will be exported.\n"+
                    "Exported list will have the suffix top_barcode_list.txt added to the FILENAME used as input",type=int)
parser.add_argument("-e","--EXPORT_PLOT", help="Boolean Value for exporting plot. Set to False when exporting Barcode list. Default is True",type=parse_bool)

args=parser.parse_args()
print(args)
